---
title: "Proposal"
author: "Qi Wang"
date: "2021/10/26"
output: 
  pdf_document:
        latex_engine: xelatex 
bibliography: red_wine.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Introduction




# 2. Our Goal of Research
Here, in this paper, we are going to explore some methods to classify the wine into different quality levels. We do not use clustering methods here but we will use logistic regression to achieve our goal. And our goal is to explore which of these variables which I will talk about in the variable description section will have a significant effect on the red wine qualification and it is positive or negative, and how much will the significant variables affect the level of the red wine qualification.


# 3. Variable Despription
There are 11 covariates and one categorical response variable. Fix acidity is the most acids involved with wine or fixed or nonvolatile (do not evaporate readily). Volatile acidity is the amount of acetic acid in wine, which at too high of levels can lead to an unpleasant, vinegar taste. Citric acid is the most important organic acid produced in tonnage by fermentation, with a taste of sour like lemons [@citric_acid]. Residual sugar is the amount of sugar left in a wine, to some extent, it measures the sweetness of a wine. Chlorides is a key role in the salty taste of a wine, which will make customers feel uncomfortable. Sulfur dioxide $(SO_2)$ is important in the wine making process as it aids in preventing microbial growth and the oxidation of wine [@sulfur_diox]. The difference between free sulfur dioxide and total sulfur dioxide is the way of measuring them. Gaseous SO2 is released from the sample by addition of acid and swept into the ICP by an argon stream. The intensity of the sulfur atomic emission lines is measured in the vacuum UV region. Determination of total $SO_2$  is performed after hydrolysis of bound forms with sodium hydroxide $(NaOH)$[@test_sulfur]. For sulfates, many experts believe that higher sulfurous content causes a duller taste in wine, and that high potency of sulfite ions presents a health risk and speeds up the wine's fermentation process. The other covariates including alcohol, pH and density are basically simple indexes of a red wine. Our response variable is an ordered categorical variable indicating the quality of red wine, from 0 to 10.

# 4. Problems When Analyzing
1. To begin with, the response variable in this data set is categorical but have 11 degrees, although in the data there are only five levels, we still need to first merge some groups to get a 0-1 variable to continue the logistic regression.

2. Then, there are some inner co linearity among the covariates. Citric acid amount is strongly positively correlated with fixed acidity. And fixed acidity is also strongly positively correlated with the density of the wine. Researches have shown that the citric acid has an effect on the acidity of the liquid, and a more concentration of citric acid means a stronger acidity [@acid].Also, the amount of free sulfur dioxide is positively correlated with the amount of total sulfur dioxide. However, there are still some negative correlations among variables. For example, the pH of the red wine is negatively correlated with the fixed acidity and the amount of citric acid in the wine. From common sense, we know a stronger acidity means a lower pH, that's why the pH is lower for those wine with more concentration of fixed acidity and citric acid. Also, larger concentration of alcohol gives a smaller density. As we know, the density of alcohol is smaller than water, so if more alcohol is included in the wine, the density must be lower than those without that much alcohol. I fixed this problem by first select variables for a base model which has weak relationships, then add variables to check the model selection criteria.

3. There are some outliers in the model, but after checking the resource of data, I don't think it is a measurement error, therefore, I just leave it there and still looking for further methods to handle it.

4. It is a logistic regression, so the residual analysis is tricky. I will begin this part after learning this method in the class.

# References {.unnumbered}